apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: argocd/middlewares/minio
    repoURL: https://github.com/OpenDataPlatform/kdc01.git
    helm:
      values: |
        minio:
          image:
            repository: minio/minio
          rootUser: "minio"
          rootPassword: "minio123"

          drivesPerNode: 4
          replicas: 4
          pools: 1

          persistence:
            enabled: true
            storageClass: "standard"
            accessMode: ReadWriteOnce
            size: 5Gi

          ingress:
            annotations:
              cert-manager.io/cluster-issuer: cluster-issuer1
              kubernetes.io/ingress.class: nginx
              kubernetes.io/tls-acme: "true"
            enabled: true
            labels: { }
            tls:
              - hosts:
                  - minio1.ingress.kind
                secretName: minio1-tls
            hosts:
              - minio1.ingress.kind
            path: /
          consoleIngress:
            enabled: true
            labels: { }
            annotations:
              cert-manager.io/cluster-issuer: cluster-issuer1
              kubernetes.io/ingress.class: nginx
            tls:
              - hosts:
                  - minio1-console.ingress.kind
                secretName: minio1-console-tls
            hosts:
              - minio1-console.ingress.kind
            path: /

          resources:
            requests:
              memory: 2Gi
  destination:
    namespace: minio1
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
